# ==========================
# MLOps Project Makefile - Integrated Version
# ==========================

PYTHON=python3
ENV_NAME=mlops_env
REQUIREMENTS=requirements.txt
DATA_FILE=productivityPrediction.csv

# Model files generated by the pipelines
PRED_MODEL_FILE=productivity_model_20251127_234333.pkl
CLASS_MODEL_FILE=productivity_classifier.pkl

# =========================================
# 1. Environment Setup
# =========================================
.PHONY: setup
setup:
	@echo "\U0001f527 Creating virtual environment and installing dependencies..."
	@$(PYTHON) -m venv $(ENV_NAME)
	@. $(ENV_NAME)/bin/activate && pip install --upgrade pip
	@. $(ENV_NAME)/bin/activate && pip install -r $(REQUIREMENTS)
	@echo "\u2705 Environment setup complete!"

# =========================================
# 2. Train Models
# =========================================
.PHONY: train-models
train-models: setup
	@echo "\U0001f3cb\ufe0f Training regression model..."
	@. $(ENV_NAME)/bin/activate && PYTHONPATH=$$PYTHONPATH:$(shell pwd) $(PYTHON) model_pipeline.py --data $(DATA_FILE) --save_model $(PRED_MODEL_FILE)
	@echo "\U0001f3cb\ufe0f Training classification model..."
	@. $(ENV_NAME)/bin/activate && PYTHONPATH=$$PYTHONPATH:$(shell pwd) $(PYTHON) randomforest.py --data $(DATA_FILE) --save_model $(CLASS_MODEL_FILE)
	@echo "\u2705 Models trained successfully!"

# =========================================
# 3. Run FastAPI Server
# =========================================
.PHONY: run-api
run-api:
	@echo "\U0001f680 Starting FastAPI server in background..."
	@. $(ENV_NAME)/bin/activate && nohup uvicorn api:app --host 0.0.0.0 --port 8000 --reload &> api.log &
	@sleep 2
	@echo "\u2705 API started (logs in api.log)"

# =========================================
# 4. Launch Dashboard (Streamlit)
# =========================================
.PHONY: run-gui
run-gui:
	@echo "\U0001f5b1 Launching MLOps Dashboard..."
	@. $(ENV_NAME)/bin/activate && streamlit run productivity_gui.py

# =========================================
# 5. Full Pipeline
# =========================================
.PHONY: all
all: train-models run-api run-gui
	@echo "\U0001f680 Full pipeline executed successfully!"

